name: PR
on:
  pull_request:
    branches:
      - master
jobs:
  check-versions:
    runs-on: self-hosted
    if: |
      ! contains(github.event.head_commit.message, '[skip ci]')
    steps:
      - uses: actions/checkout@v2
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: compare versions
        id: comp_ver
        run: |
          cd scripts
          npm ci
          node exec_versions.js
  test-build:
    needs: check-versions
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: build-docker
        run: |
          ./scripts/dockerbuild.sh
